### PR TITLE
feat(ci): publish arm64 images

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Build and publish and arm64 image as outlined here https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

### CODE REVIEW

**Comment by emmaindal** [comment]
Hello @johanneswuerbach thanks for the contribution. Can I just ask you to explain your use case a bit for me?

**Comment by johanneswuerbach** [comment]
Hey @emmaindal, I'm running on an M1 Mac so having an image, which runs natively on that architecture would be preferred.

There also seem to be issues with a strange graphviz output, if the amd64 image is running under emulation.

**Comment by emmaindal** [comment]
> Hey @emmaindal, I'm running on an M1 Mac so having an image, which runs natively on that architecture would be preferred.
> 
> There also seem to be issues with a strange graphviz output, if the amd64 image is running under emulation.

thanks for the context, let us just discuss this in the team quickly and we will get back to this PR!

**Review by emmaindal — APPROVED** [review]
This looks good to us, thanks for the contribution! @johanneswuerbach

**Pull request merged**
